[package]
name = "backend-authentication"
version = "0.1.0"
description = ""
keywords = ["daswag"]
edition.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"

[dependencies]
